 name: .NET CI/CD Pipeline

 on:
   push:
     branches:
       - master
   pull_request:
     branches:
       - master

 jobs:
   build-and-test:
     name: Build and Test
     runs-on: ubuntu-latest

     steps:
       # Step 1: Checkout the code
       - name: Checkout code
         uses: actions/checkout@v3

       # Step 2: Set up .NET
       - name: Set up .NET
         uses: actions/setup-dotnet@v3
         with:
           dotnet-version: 8.0.x

       # Step 3: Restore dependencies
       - name: Restore dependencies
         run: dotnet restore

       # Step 4: Build the project
       - name: Build the project
         run: dotnet build --no-restore --configuration Release

       # Step 5: Run tests
       - name: Run tests
         run: dotnet test --no-build --configuration Release --logger "trx;LogFileName=test-results.trx"

       # Step 6: Upload test results (optional)
       - name: Upload test results
         if: always()
         uses: actions/upload-artifact@v4  # Updated to v4
         with:
           name: test-results
           path: "**/TestResults/*.trx"
           retention-days: 5  # Added retention period

   deploy:
     name: Deploy
     runs-on: ubuntu-latest
     needs: build-and-test
     if: github.ref == 'refs/heads/master'

     steps:
       # Step 1: Checkout the code
       - name: Checkout code
         uses: actions/checkout@v3

       # Step 2: Deploy (placeholder for deployment steps)
       - name: Deploy application
         run: echo "Add your deployment steps here (e.g., Azure, AWS, or other platforms)"
